### ISSUE TITLE
Installed but not showing in VS Code anymore

### ISSUE THREAD

**Issue by ryanhelms** [prashaantt/node-tdd#13]
Hello,

  I have been waiting to use your plug-in. It seems like just the tool that I need for my serverless development. When I first installed it, I saw it  per your video in the status bar. However, now that I want to use it, it is not there. I have tried to uninstall, reinstall, etc and I can get it installed but it  doesn't show up. I have checked that it is enabled, etc as well and it is.  If you have any insight as to why it would not be in the status bar anymore I would greatly appreciate it. I will attach a few screenshots below for your reference.

What the status bar looks like:
![image](https://cloud.githubusercontent.com/assets/1596639/26644678/8962f820-4603-11e7-9d89-ae5bdfd785e0.png)

What the extension status is:
![image](https://cloud.githubusercontent.com/assets/1596639/26644723/bae015cc-4603-11e7-900b-c17577a26f0f.png)

Version Information:
![image](https://cloud.githubusercontent.com/assets/1596639/26644737/c4e4c676-4603-11e7-95ee-9d12db0714df.png)

Looking forward to fixing this soon!

Cheers,
Ryan

**Comment by prashaantt** [comment]
`package.json` needs to be in the project root for this plugin (as well as most of Node.js) to work.

Also, I see you're using Windows, which has currently some issues — [this thread](https://github.com/prashaantt/node-tdd/issues/5) gives more context with a temporary fix.

**Comment by ryanhelms** [comment]
Prashaantt,

Thanks a lot for the reply. I was able to get the plug-in to load when I made the root the /src folder. It is not running tests, but I am sure that has to do with the Windows issues which I will review now. Thanks again and great work.

Cheers,
Ryan
