### ISSUE TITLE
TDD is not working on my windows machine

### ISSUE THREAD

**Issue by skumar568** [prashaantt/node-tdd#14]
Hi @prashaantt ,

I have Visual Studio Code v1.15.1 with Node TDD plugin. I can see the symbol in status bar which means that it is activated. However, it is not getting invoked at all. Am I missing something? It is not very clear from project readme.
![vscodetdd](https://user-images.githubusercontent.com/24720105/29590612-9d45b9d8-8792-11e7-8608-d4f8e0a6f60e.png)

Thanks,
Sanjeev

**Comment by prashaantt** [comment]
I'm sorry. This is a known issue. Until I have a proper fix published, please find a solution in [this thread](https://github.com/prashaantt/node-tdd/issues/5), which also tracks this bug.
