### ISSUE TITLE
Add option to explode spectacularly but succeed silently

### ISSUE THREAD

**Issue by Olian04** [prashaantt/node-tdd#16]
I've only recently found node-tdd and I've got to say, this might just change how i develop software.
I would however like to see an option to display failed builds in a more visual manner. 
If a build is successful the green check-mark is absolutely enough, but when a build fails i want to know about it immediately and spectacularly (on my 4k laptop display the little "Failing" text is about 4mm (0.15") tall).

It doesn't even have to be that fancy to begin with, just allowing for a verbose output if the build fails would be enough.

**Comment by prashaantt** [comment]
Did you try the `nodeTdd.verbose` option?

**Comment by Olian04** [comment]
Adding the verbose option would enable verbose mode for successful results as well. Witch i don't want.

**Comment by prashaantt** [comment]
OK, that can be fixed easily. If you can live with it for now, I can do
something about it in the next release.

**Comment by prashaantt** [comment]
Your wish has been granted! Please check out the latest version with updated `verbose` setting with `{onlyOnFailure: true}` option.
