### ISSUE TITLE
Issue Running on Windows 10

### ISSUE THREAD

**Issue by JohnBloom** [prashaantt/node-tdd#18]
Really excited about this extension. However I have yet to get it to work. I opened a typescript workspace with a package.json and nothing happens. Here are some things I have observed:

- I checked the TDD output and it isnt outputting any information. 
- I have changed some settings but it doesnt seem to do anything.
- I am on windows 10 and on the latest VS Code.
- I have opened multiple workspaces and the result is the same

I would love to supply some logs or some debug information if you can point me where to find them.

**Comment by JohnBloom** [comment]
Ok something kicked in and now it is doing the building issue in #5. Closing this. Would be nice if that fix was brought in.

**Comment by prashaantt** [comment]
Please check out the latest version.
