### ISSUE TITLE
Results shown in output are not displayed correctly

### ISSUE THREAD

**Issue by drackp2m** [prashaantt/node-tdd#25]
I have seen that many characters do not look good.

![image](https://user-images.githubusercontent.com/12443324/46813235-a69de200-cd76-11e8-839b-cdab314a817c.png)

This has not happened to me with any other plugin, and I do not know if someone else could have happened.

**Comment by vpillinger** [comment]
As far as I can tell this is because your test runner returns colorized output. However, this output console does not have the ability to display colorized output, so you see a bunch of color related junk displayed.
