### ISSUE TITLE
Stuck in building...

### ISSUE THREAD

**Issue by MWallin** [prashaantt/node-tdd#5]
When I activate the extension nothing happens except the text building... keeps rolling over and over. 

The npm script that is refered in setting works manually. When I look at output for the extension there is none. 

Any help would be super nice!

**Comment by prashaantt** [comment]
That's interesting, can you show me what the script looks like?

**Comment by MWallin** [comment]
Sure thing!

    "test": "mocha **/*.test.js"

I am totally new to testing so might it be something wrong with my tests? I am following a tuturial wich uses mocha and expect.

**Comment by prashaantt** [comment]
That looks pretty standard. Can you try removing some tests to prove that at least the thing works for one test?

The best guess I can make is that there's probably an infinite loop in some test that's not letting the process to exit.

**Comment by MWallin** [comment]
No luck I'm afraid. 

This is the file I'm writing tests for

```
"use strict"

// *****************************************************************************
// *****************************************************************************
// Functions here

function add ( a, b ) {

  return a + b

}

function square ( a ) {

  return a * a

}



// *****************************************************************************
// *****************************************************************************
// Exports

module.exports = {

  add,
  square

}

```

And these are the tests I'm trying to write...

```
"use strict"

// *****************************************************************************
// *****************************************************************************
// Requires

const expect = require( "expect" )



// *****************************************************************************
// *****************************************************************************
// File to be tested

const utils = require( "./utils" )



// *****************************************************************************
// *****************************************************************************
// Tests

// Add function
it( "Should add two numbers", () => {

  const result = utils.add( 33, 11 )

  expect( result ).toBeA( "number" ).toBe( 44 )

})


// Square function
it( "Should square 1 number", () => {

  const result = utils.square( 6 )

  expect( result ).toBeA( "number" ).toBe( 36 )

})

```


Could I have set some configuration wrong? These are my settings on top of the default...
```
  //NodeTDD
  "nodeTdd.reporter": null,
  "nodeTdd.buildOnCreate": true,
  "nodeTdd.verbose": true,
  "nodeTdd.glob": "**/*.test.js",
  "nodeTdd.buildOnActivation": true
```

**Comment by prashaantt** [comment]
`"nodeTdd.glob": "**/*.test.js"` — you'll want to watch changes to source files too, not just the tests.

`"nodeTdd.buildOnCreate": true` — it doesn't look like it applies in this case but if your tests have any side effect of creating files that match the glob, they will get watched too, perhaps leading to an infinite build loop.

I don't see any other issues and your code works for me as expected. What OS are you on? Are you able to stop the build process? If not, try killing it from the terminal to confirm if it's not a bad process from the past that's just refusing to die.

**Comment by prashaantt** [comment]
I don't know your OS but I just released a new version that *may* potentially fix an issue on Windows as a side-effect.

**Comment by MWallin** [comment]
I'm on Windows 10 Pro and the updated version didn't exactly fix the issue, it did however bring some error messages. 

I did a reboot to make sure no bad processes were running. And now when I'm tryig to stop the build process I get:

`Running the contributed command:'nodeTdd.stopBuild' failed.`

And then this when I try do deactivate. 

`Running the contributed command:'nodeTdd.deactivate' failed.`

No other output however and no error when starting build. 

Is there anything else I might do to help resolve this?

**Comment by prashaantt** [comment]
Whoa that's a bug — this has got to do with the differences between how Windows and POSIX systems handle processes. I just tried a fix, would you mind testing [this vsix](https://www.dropbox.com/s/3wiyyzomzhvqljl/node-tdd-0.2.3.vsix?dl=0) out for me? [Here are the instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-from-a-vsix) on how to do it.

**Comment by MWallin** [comment]
Sorry to be that guy, but one step forward, one step backwards...

Succesfull installation and no error messages this time around. However, the original problem with building not completing is still there. And there is no way for me to stop the build process either, and again no output at all. 

Are there any logging on my machine that might help you or anything else I might do?

I've waited for the build to complete now for a couple of minutes, should that be enough or am I impatient?

**Comment by prashaantt** [comment]
Do you mind pushing your project somewhere on GitHub so we can rule out any config issues? The `npm-debug.log` is generated only for test failures for non-standard script names (i.e. other than `test`) so we have nothing else to go by.

The build for 2-odd tests should finish in milliseconds.

**Comment by prashaantt** [comment]
By the way, even if the build doesn't stop you should be able to still see some text output from the tests if you open the output view (View > Output) and select the TDD Extension from the dropdown.

**Comment by MWallin** [comment]
I had some extra files like eslint config and stuff like that originally but stripped them out, without change however. Here is the current project: https://github.com/MWallin/Test_basics 

Testing works fine from the console. 

There is no output at all from TDD, see printscreen. No change if I deactivate and activate. 

![image](https://cloud.githubusercontent.com/assets/3184624/22397343/a19cc42e-e56f-11e6-9508-2e351e23d132.png)

**Comment by prashaantt** [comment]
It would have been cool if you pushed your entire workspace as it is, including the .vscode folder where you are possibly overriding the default nodeTdd settings and any other js files that may be also present. I'm a little curious also to see how you're using the other test script with `nodemon` in it, if at all — `nodemon` is a long-running process and will not work right with this extension.

But as things stand, your project works perfectly on my Mac. :/

**Comment by MWallin** [comment]
Sorry for that, thought the basic example would be easier to debug. Here is the complete workspace: https://github.com/MWallin/Test_basics2

Lots of files in there thats not really necessary, I use the same basic scaffold for every new project, perhaps a bad practice, but easier to copy the config than redo from scratch each time...

The other testscript is a trick from the course I'm taking. Basically it does what you extension does but in a separate console window, when it detects a change in any file it reruns the npm test script. That way works but I thought it a bit clumpsy and found this extension. 

I don't have nodemon running while trying you extension so that should'nt be the source of the problem. 

If you can't figure it out now I thank you for the effort so far! Really nice of you trying to help me!

**Comment by prashaantt** [comment]
Nope, still can't figure out a thing. I'm going to leave a note about potential issues on Windows with this extension and hope you or someone else can debug it for us :) Thanks.

**Comment by btmurrell** [comment]
hi @prashaantt --  i am having this issue right now too.  I know what is causing mine, and i see a negative side effect.  when i open the TDD console, i see an error: `Error: listen EADDRINUSE :::5858` this is because my npm test command has `--debug` on it, *and* i have my app running in another window with `--debug`.  This error in TDD is to be expected...  however, i went and killed my running app in the other window (releasing the debug port) but TDD is still stuck.  It would be nice to have a way to restart the TDD task.  I suspect if I exit Code and restart, all will be fine.  Just wanted to offer this feedback.  I am on OSX.

all said, this is a GREAT plugin.  I like having this in lieu of setting up my own grunt/gulp watch for TDD.

**Comment by prashaantt** [comment]
@btmurrell Are you able to stop the build by click on the status bar? And it appears your issue should have nothing to do Windows specifically, but it won't hurt to ask — what OS are you on?

It would be awesome if you're able to set up a quick project for me to debug.

**Comment by stherrienaspnet** [comment]
Hello prashaant,
I'm using windows 7 and would be nice to use your plugin. Did anyone get it working with windows 7?

**Comment by ghost** [comment]
Hi, I seem to have the same issue on Win10 pro. I get no output anywhere.
Started from powershell directly via "npm run test", the tests run as expected. If it helps in any way I could push the workspace where this is happening into github. The setup is very basic however, since i just started to get familiar with testing.

**Comment by prashaantt** [comment]
I'll try to get hold of a Windows computer soon to figure this thing out.

**Comment by prashaantt** [comment]
@MWallin @stherrienaspnet @theweekendgeek I finally got hold of Windows and attempted a fix. Can you please try [this vsix](https://www.dropbox.com/s/rbdzoghldaibzaa/node-tdd-0.2.4.vsix?dl=0)? The instructions to install are provided earlier in this thread.

**Comment by MWallin** [comment]
Nice work! 

The build completes and the tests run now, just as if I would have run them myself. 

However, the watch part of the extension doesn't seem to be working. This is my glob pattern  /**/*.js  which I think should trigger a build whenever I save a .js file?

**Comment by ghost** [comment]
Thanks a lot! 
For me it works the same as @MWallin says. The build completes and I can see the test results. Saving of files, however, does not automatically trigger a new build. I have not changed the glob pattern and am using the src and test diretories for my app Code and Tests.

**Comment by prashaantt** [comment]
Great, so we are partly there (though I still don't know the edge cases that can bite us here). But I've had no trouble in getting my globs to work right, just remember two things:

1. The glob is relative to the workspace (as also recorded in the docs), so `/**/*.js` is not likely to work, but `**/*.js` does work for me, assuming all the source/test files are nested one level deeper to root.
2. Whenever you fiddle with the glob setting, just ensure to re-activate the extension for the change to take effect. (I'll try fixing this requirement.)

**Comment by MWallin** [comment]
Hm, there seems to still be something fishy with the globs. It just won't work for me.

My workspace structure is as follows:

```
Project root
  server
    utils
      message.js
  tests
    utils
      message.test.js
```

There are some more stuff in there but these two files are the ones related to the testing. The whole project can be found here: https://github.com/MWallin/socket-io-chat-app

When I load the workspace everything works fine and the tests run. But it wont watch and rerun. The glob I'm using is:   "nodeTdd.glob": "**/*.js"


Just to be clear. I am right to asume that the watch function should automaticly trigger a build whenever a file matching the glob is saved?

**Comment by prashaantt** [comment]
> Just to be clear. I am right to asume that the watch function should automaticly trigger a build whenever a file matching the glob is saved?

Yes, that's of course the whole point.

I'm getting different results for the watch mode on Win and Mac platforms. `**/*.js` works as expected for all files embedded at any level of depth from the root on Mac, but to get your project structure to trigger a build it needs me to change it to `**/**/*.js` (or more specifically `{server,tests}/**/*.js`) on Win. I have unfortunately no influence on this behaviour as these file change events are triggered by VS Code, which I'm then listening for to spawn the build.

**Comment by ghost** [comment]
I works now for me, whether i use `**/*.js` or `**/**/*.js`, thanks a lot! 
~~One more question though, is it possible to somehow disable the message that VS Code displays on top? I would prefer only to have the feedback via the status bar.~~

edit: nevermind: I still had the verbose option enabled!

**Comment by prashaantt** [comment]
Cool. If it continues to work well enough for y'all, I'll make a new release.

**Comment by MWallin** [comment]
Works just fine with the new blob `{server,tests}/**/*.js`

Really great work @prashaantt!

**Comment by schwaerz** [comment]
Hi there,

Just encountered the issue described here (tests won't run at all - I just see Building...).
Is the fix supposed to be already included in the latest version available in the vscode gallery (2.3.0)?
Would be great if I could use this plugin esp. as I'm now about to start with a new project.

Thanks

**Comment by unpollito** [comment]
I had the same issue on W7 Ultimate: the extension was just stuck in Building, but with the 0.3.24 version, the tests run just fine.

On an unrelated topic, I find it surprising that the documentation claims that only the TAP reporter is supported. I have tried running the tests with the Karma "dots" reporter and it seems to work just fine as well.

**Comment by prashaantt** [comment]
> Is the fix supposed to be already included in the latest version available in the vscode gallery

@schwaerz I intended to push the fixes worked out in this issue but realised they seemed issues with Node/VS Code itself rather than the extension so I didn't yet. I haven't been able to find time to debug this properly to send them a bug report. If you wish, you can use the unofficial 0.3.24 build linked a few issues above for now.

**Comment by prashaantt** [comment]
> I have tried running the tests with the Karma "dots" reporter

@unpollito Isn't the dots reporter just a unit test reporter and not a coverage reporter? The `reporter` setting is used only for selecting the test coverage reporter.

**Comment by schwaerz** [comment]
I'll give it a shot. Unfortunately I cannot download the intermediate version right from this PC as all the file sharing is blocked here.
I'll try using my mobile instead.

**Comment by schwaerz** [comment]
Looks like the link to the unofficial build does no longer work...
Is the fix in the repository? I could try doing my own build.

**Comment by prashaantt** [comment]
@schwaerz [This link](https://www.dropbox.com/s/rbdzoghldaibzaa/node-tdd-0.2.4.vsix?dl=0) still works for me.

**Comment by jimrock** [comment]
thanks, and to use 0.2.4 to fixed my windows 10 issue, but seems still not release out this version to the market?

**Comment by Wolfium** [comment]
Custom release 0.2.4 worker like a charm on windows, current release doesn't.

Would you mind, if possible, to update published version to latest 0.2.4 on VsCode Marketplace?

Thanks in advance for great an slick extension to promote TDD.

Regards

**Comment by prashaantt** [comment]
Hey, I'm sorry it's getting delayed. I will test this on the latest version of Code on Windows to see if the bug in Code is fixed, if not I'll release with my own patch within a couple of weeks.

**Comment by HeinousTugboat** [comment]
That vsix from dropbox is working for me on Windows 10, the version in the marketplace was doing the same thing as the others.

**Comment by prashaantt** [comment]
I just published v0.2.4 that tries to fix this issue. Please give it a spin and let me know.

**Comment by schwaerz** [comment]
Thanks for updating the plugin :) I'm now able to run the tests using node TDD.
Unfortunately it won't notice any changes in any of my test or source files. According to the "glob" pattern I assume it should:
```
"nodeTdd.glob": "{src,specs}/**/*.{js,ts,jsx,tsx}"
```
Source files are located below 'src', tests are in 'specs'.

**Comment by prashaantt** [comment]
Did you try disabling and re-enabling the plug-in after changing the glob
settings?

Edit: I meant de-/activating.

**Comment by schwaerz** [comment]
Thanks for the quick response. It's working now :smiley: 
Did: Disable plugin, reload, enable plugin, reload. Smile.

**Comment by prashaantt** [comment]
@schwaerz If by reload you mean window reload, you can safely skip that step. Just disabling and enabling back on through the TDD button should be sufficient 😊

Once more people test this out and report their findings, we can close this issue out for good.
