### ISSUE TITLE
Support custom scripts instead just npm tasks

### ISSUE THREAD

**Issue by ghost** [prashaantt/node-tdd#7]
Maybe you could allow the user to specify which command to execute for a test and also take a filepath that just contains a coverage value ("87.95") and then use those values to output the data. that way one could write wrappers for any language/framework and use it very easily. the extension itself is really beautiful so it would be a shame not being able to use it because of other languages.

**Comment by prashaantt** [comment]
Thanks, I'm happy you like it. :)

Focusing exclusively on Node and TDD allowed me to limit the activation point (presence of `package.json` in the workspace) and the feature path I'm able to work on (things like the reporter). For more generic use cases you can take a look at [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave), which inspired me to create this.

**Comment by ghost** [comment]
Well that is kinda understandable. I tried bridging this by creating a bare package.json with a reference to my test command. It works. I wrote a TAP wrapper for my test runner output and even that one works. 

Though one thing is kinda strange. Node-TDD always displays one more Test than there actually is. My test runner outputs this: 

> ?   	internal/somepath/src/cmd/main	[no test files]
=== RUN   TestPkg
ok 0 Some random test
ok 1 Some other test
ok 2 Yet another test
--- PASS: TestPkg (0.00s)
PASS
coverage: 78.3% of statements
ok  	internal/somepath/src/pkg	0.006s	coverage: 78.3% of statements

But node-Tdd says 4/4 tests passed (always 1 more than there actually is). In the beginning I even had that (0..2) TAP thing but I removed it which made no difference at all.

Sorry for taking your time with something that wasn't even supposed to work but as said I really like your extension. It even allowed me to change my testing framework since the older one I used had a WebUI which was the main reason for using it. This is the first time I ever had that there is not one single reason to switch out of your editor/ide (without having multiple terminals open in your editor...) and it feels wonderful

Edit:// I just realized the last ok. I discarded the last line and now it shows the proper test number. My fault. Thanks for the wonderful extension.

**Comment by prashaantt** [comment]
No problem, cool if it works for you!

By the way, are you Windows by any chance? I'd love it to be tested on Windows, because I fear there may be [some issues](https://github.com/prashaantt/node-tdd/issues/5).

**Comment by ghost** [comment]
Sorry no I'm on Linux. Didn't touch a Windows computer in years :laughing: 
Though I had the same problem with my code in the beginning (extension showed that its building but never returned). It never returned since the tests sync executed something that never returned and as thus blocked forever.  You could output the command your extension is about to execute and let the Windows user manually execute that command to see what happens.
