### ISSUE TITLE
Terminal output setting

### ISSUE THREAD

**Issue by nicosommi** [prashaantt/node-tdd#9]
It would be nice to have a terminal instead of the output when toggle the status, because of the current vscode limitation about colors on the output window:

See here:
https://github.com/Microsoft/vscode/issues/243

Check out the comment from bartlewis he says how to open a new terminal by sending a command to execute.

This would be great to see the colors on the tests reports, which are very important.

**Comment by prashaantt** [comment]
From the same comment you mention:

> This is not ideal, as it spawns a new Terminal window each time.

So I'd wait for colours to be officially supported in the output channel itself.

You can try the [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extension or similar to achieve what you want.

**Comment by nicosommi** [comment]
It is almost two years old. But ok. Thanks anyway
